# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b93ead86c02fd938991d2b11570e162c40a6d269b3f56fcdb0abf6635224edd9f557ea2f3c033436a3f50b9dfc8cbbd488ce89c88b356f9b0f77474d4c3d7328

test:
  secret_key_base: ea2c21fd6f9705289d3918cea142a73227fb05cc5e1e9a3bca368be367126431f0952484bb76927cd0592617f5d30af480171fe544d94c6fdab7ef405fbb1c88

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
